# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       stellarium-sf

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Night sky viewer
Version:    0.9.1
Release:    1
Group:      Qt/Qt
License:    Stellarium for Sailfish and Stellarium N9 - Copyright (C) 2012-2015 Marko Srebre; Stellarium 0.12.4 - Copyright (C) 2004-2013 Fabien Chereau et al; GNU General Public License version 2

URL:        http://example.org/
Source0:    %{name}-%{version}.tar.bz2
Source100:  stellarium-sf.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(sailfishapp) >= 0.0.10

%description
Stellarium for Sailfish is based on desktop version of Stellarium 0.12.4, providing some additional features such as native QML gui, sensor based orientation and customized graphics engine settings. It is still work in progress, but most of the basic things should work just fine.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
/usr/bin
/usr/share/stellarium-sf/data
/usr/share/stellarium-sf
/usr/share/stellarium-sf/stars
/usr/share/applications
/usr/share/icons/hicolor/86x86/apps
/usr/share/stellarium-sf/qml
# >> files
# << files
